CREATE SCHEMA IF NOT EXISTS DEV01;

DROP TABLE DEV01.USER_ACCOUNT;
DROP TABLE DEV01.PRODUCT;

CREATE TABLE IF NOT EXISTS DEV01.USER_ACCOUNT
(
	USER_ID INT AUTO_INCREMENT
		PRIMARY KEY,
	USER_NAME VARCHAR(30) NOT NULL,
	GENDER VARCHAR(1) NOT NULL,
	PASSWORD VARCHAR(30) NOT NULL,
	CONSTRAINT USER_ACCOUNT_USER_NAME_UINDEX
		UNIQUE (USER_NAME)
);

CREATE TABLE IF NOT EXISTS DEV01.PRODUCT
(
	PRODUCT_CODE VARCHAR(20) NOT NULL,
	PRODUCT_NAME VARCHAR(128) NOT NULL,
	PRODUCT_PRICE FLOAT NOT NULL,
	PRODUCT_ID INT AUTO_INCREMENT
		PRIMARY KEY,
	CONSTRAINT PRODUCT_CODE_UINDEX
	UNIQUE (PRODUCT_CODE)
);


