INSERT INTO DEV01.USER_ACCOUNT (USER_NAME, GENDER, PASSWORD) VALUES ('Cody', 'M', 'Password');
INSERT INTO DEV01.USER_ACCOUNT (USER_NAME, GENDER, PASSWORD) VALUES ('Josh', 'M', 'Password');
INSERT INTO DEV01.USER_ACCOUNT (USER_NAME, GENDER, PASSWORD) VALUES ('Mitch', 'M', 'Password');
INSERT INTO DEV01.USER_ACCOUNT (USER_NAME, GENDER, PASSWORD) VALUES ('Maria', 'F', 'Password');
INSERT INTO DEV01.USER_ACCOUNT (USER_NAME, GENDER, PASSWORD) VALUES ('Lauren', 'F', 'Password');
INSERT INTO DEV01.USER_ACCOUNT (USER_NAME, GENDER, PASSWORD) VALUES ('Test', 'T', 'Password');


INSERT INTO DEV01.PRODUCT (PRODUCT_CODE, PRODUCT_NAME, PRODUCT_PRICE) VALUES ("P001", "Product 1", 1.99);
INSERT INTO DEV01.PRODUCT (PRODUCT_CODE, PRODUCT_NAME, PRODUCT_PRICE) VALUES ("P002", "Product 2", 2.99);
INSERT INTO DEV01.PRODUCT (PRODUCT_CODE, PRODUCT_NAME, PRODUCT_PRICE) VALUES ("P003", "Product 3", 3.99);
INSERT INTO DEV01.PRODUCT (PRODUCT_CODE, PRODUCT_NAME, PRODUCT_PRICE) VALUES ("P004", "Product 4", 4.99);
INSERT INTO DEV01.PRODUCT (PRODUCT_CODE, PRODUCT_NAME, PRODUCT_PRICE) VALUES ("P005", "Product 5", 5.99);