INSERT INTO DEV01.USER_ACCOUNT (USER_NAME, GENDER, PASSWORD) VALUES ('Cody', 'M', 'Password');
INSERT INTO DEV01.USER_ACCOUNT (USER_NAME, GENDER, PASSWORD) VALUES ('Josh', 'M', 'Password');
INSERT INTO DEV01.USER_ACCOUNT (USER_NAME, GENDER, PASSWORD) VALUES ('Mitch', 'M', 'Password');
INSERT INTO DEV01.USER_ACCOUNT (USER_NAME, GENDER, PASSWORD) VALUES ('Maria', 'F', 'Password');
INSERT INTO DEV01.USER_ACCOUNT (USER_NAME, GENDER, PASSWORD) VALUES ('Lauren', 'F', 'Password');
INSERT INTO DEV01.USER_ACCOUNT (USER_NAME, GENDER, PASSWORD) VALUES ('Test', 'T', 'Password');